trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'hellokube:$(build.buildId)'

steps:
- script: docker build -f ./src/HelloKube/Dockerfile -t $(imageName) ./src/HelloKube
  displayName: 'docker build'
